services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home
    environment:
      - JENKINS_OPTS="--httpPort=8080"

  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - nginx-proxy-manager-data:/data
      - nginx-proxy-manager-letsencrypt:/etc/letsencrypt
    restart: always

volumes:
  jenkins_home:
  nginx-proxy-manager-data:
  nginx-proxy-manager-letsencrypt: